#!/bin/bash

cd ..
mvn clean package
cp -a common/target/classes/ newCarsSender/target/classes
rm -r newCarsSender/target/uber/common-1.0-SNAPSHOT.jar
cp -a common/target/classes/ carsFilter/target/classes
rm -r carsFilter/target/uber/common-1.0-SNAPSHOT.jar
cp -a common/target/classes/ carsReceiver/target/classes
rm -r carsReceiver/target/uber/common-1.0-SNAPSHOT.jar
cp -a common/target/classes/ newCarsCreator/target/classes
rm -r newCarsCreator/target/uber/common-1.0-SNAPSHOT.jar
jar cfm Sender.jar newCarsSender/src/main/java/META-INF/MANIFEST.MF -C newCarsSender/target/classes .
jar cfm Filter.jar carsFilter/src/main/java/META-INF/MANIFEST.MF -C carsFilter/target/classes .
jar cfm Consumer.jar carsReceiver/src/main/java/META-INF/MANIFEST.MF -C carsReceiver/target/classes .
jar cfm CarFactoryServer.jar newCarsCreator/src/main/java/META-INF/MANIFEST.MF -C newCarsCreator/target/classes .
cp -r Sender.jar newCarsSender
cp -r Filter.jar carsFilter
cp -r Consumer.jar carsReceiver
cp -r CarFactoryServer.jar newCarsCreator